###### ROS Bag Recording Parameters ######
# Recorded Topics
recorded_topics: ['HumanPose','/UAV1PoseUWB','/UAV2PoseUWB','uav1/mavros/local_position/pose','uav2/mavros/local_position/pose','uav1/aft_mapped_to_init','uav2/aft_mapped_to_init','/uav1/t265teaming_planner/assigned_virtual_position','/uav2/teaming_planner/t265assigned_virtual_position','/uav1/mavros/setpoint_position/local','/uav2/mavros/setpoint_position/local','/uav1/whole_trajectory_pose''/uav2/whole_trajectory_pose','/uav1/final_trajectory_pose','/uav2/final_trajectory_pose']
# 'drone1_uwb', 'drone2_uwb', 'human_uwb', 'footIMU/IMU', 'imu_odometry', 't265/odom/sample', 'command', 'HumanPose', 'HumanPath', 'UAV1Pose', 'UAV1Path', 'UAV2Pose', 'UAV2Path', 'borealis/command/pose', 'uav1/follow_me_target_odom', 'uav1/gun_target_odom', 'uav1/target_odom', 'uav1/odom', 'uav2/odom', '/tf'
#, '/d435i/depth/image_rect_raw'

# Saved Directory
saved_directory: "/home/kw/Bag3"


###### Target Publisher Parameters  ######
# FollowMe / Go Command Topic
command_topic: '/command_mode'
# Commands
follow_me_cmd: 'Follow'
go_cmd: 'Go'


###### Human Parameters #####
human_foot_imu_topic: /footIMU/IMU
human_odometry_topic: /imu_odometry
human_uwb_topic: /human_uwb0
human_odometry_enable_service: /human_ros_launcher/odometry
human_odometry_fusion_enable_service: /human_ros_launcher/fusion
human_glove_enable_service: /human_ros_launcher/glove
human_gun_enable_service: /human_ros_launcher/rifle
human_hri_enable_service: /human_ros_launcher/hri
human_drone_yaw_control_enable_service: /human_ros_launcher/drone_yaw_control
human_uwb_enable_service: /human_ros_launcher/uwb
###### UAV 1 Parameters #####
uav1_uwb_topic: /UAV1PoseUWB
uav1_odometry_topic: /uav1/aft_mapped_to_init #/uav1/t265/odom/sample
uav1_target_topic: /uav1/mavros/setpoint_position/local
uav1_uwb_enable_service: /uav1_ros_launcher/uwb
uav1_datafeed_enable_service: /uav1_ros_launcher/datafeed
###### UAV 2 Parameters #####
uav2_uwb_topic: /UAV2PoseUWB
uav2_odometry_topic: /uav2/aft_mapped_to_init
uav2_target_topic: /uav2/mavros/setpoint_position/local
uav2_uwb_enable_service: /uav2_ros_launcher/uwb
uav2_datafeed_enable_service: /uav2_ros_launcher/datafeed
###### UAV 3 Parameters #####
uav3_uwb_topic: /UAV3PoseUWB
uav3_odometry_topic: /uav3/aft_mapped_to_init
uav3_target_topic: /uav3/mavros/setpoint_position/local
uav3_uwb_enable_service: /uav3_ros_launcher/uwb
uav3_datafeed_enable_service: /uav3_ros_launcher/datafeed

